In [43]:
##pandas##
import pandas as pd

data = {'col1':[1,2] , 'col2':[3, 4]}
df = pd.DataFrame(data=data)
df

   col1  col2
0     1     3
1     2     4

In [44]:
import numpy as np
df2 = pd.DataFrame(np.array([[1,2,3] , [4,5,6],[7,8,9]]), ###each sub list represent row of table
      columns =['a','b','c'] , index = ['x','y','z'])
df2

   a  b  c
x  1  2  3
y  4  5  6
z  7  8  9

In [45]:
df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [46]:
##print class of first row
print(type(df.iloc [0]))
##print class of name column##iloc integer-location based position
print (type(df['Name']))

<class 'pandas.Series'>
<class 'pandas.Series'>

In [47]:
titanic = df
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [48]:
titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [49]:
titanic.shape##check the number of rows and column

(891, 12)

In [50]:
titanic.info()##summary information

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [51]:
titanic['Age']###returning series obj of that column

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [52]:
titanic.Age##dot notation

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [53]:
##to select multiple columns of dataframe by name use bracket notation
titanic[['Name' ,'Age']]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [54]:
titanic.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [55]:
titanic.iloc[[0]]###single row at index 0

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [56]:
##for range of rows by enterning indices of entering and ending row
titanic.iloc[0:3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [57]:
###subset of rows and coumns
titanic.iloc[0:3,[3,4]]

                                                Name     Sex
0                            Braund, Mr. Owen Harris    male
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2                             Heikkinen, Miss. Laina  female

In [58]:
titanic.iloc[:, [3]]

                                                  Name
0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
..                                                 ...
886                              Montvila, Rev. Juozas
887                       Graham, Miss. Margaret Edith
888           Johnston, Miss. Catherine Helen "Carrie"
889                              Behr, Mr. Karl Howell
890                                Dooley, Mr. Patrick

[891 rows x 1 columns]

In [59]:
titanic.iloc[0, 3]

'Braund, Mr. Owen Harris'

In [60]:
titanic.loc[1:3, ['Name']]

                                                Name
1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2                             Heikkinen, Miss. Laina
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)

In [61]:
##for adding new column to df
titanic['Age_plus-100']= titanic['Age'] + 100
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_plus-100
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,122.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,138.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,126.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,135.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,135.0

In [62]:
##boolean masking
data ={' planet': ['Mercury' , 'Vanus', 'Earth', 'Mars', 'Jupiter', 'Setrun', 'Uranus', 'Neptune'],
      ' radius_km': [2440,6052,6371,3390,69911,58232,25362,24622],
       'moons':[0,0,1,2,80,83,27,14]}
planets = pd.DataFrame(data)
planets

    planet   radius_km  moons
0  Mercury        2440      0
1    Vanus        6052      0
2    Earth        6371      1
3     Mars        3390      2
4  Jupiter       69911     80
5   Setrun       58232     83
6   Uranus       25362     27
7  Neptune       24622     14

In [63]:
mask = planets['moons'] < 20
mask

0     True
1     True
2     True
3     True
4    False
5    False
6    False
7     True
Name: moons, dtype: bool

In [64]:
planets[mask]

    planet   radius_km  moons
0  Mercury        2440      0
1    Vanus        6052      0
2    Earth        6371      1
3     Mars        3390      2
7  Neptune       24622     14

In [65]:
planets[planets['moons']<20]

    planet   radius_km  moons
0  Mercury        2440      0
1    Vanus        6052      0
2    Earth        6371      1
3     Mars        3390      2
7  Neptune       24622     14

In [66]:
planets

    planet   radius_km  moons
0  Mercury        2440      0
1    Vanus        6052      0
2    Earth        6371      1
3     Mars        3390      2
4  Jupiter       69911     80
5   Setrun       58232     83
6   Uranus       25362     27
7  Neptune       24622     14

In [67]:
moons_under_20 = planets[mask]
moons_under_20

    planet   radius_km  moons
0  Mercury        2440      0
1    Vanus        6052      0
2    Earth        6371      1
3     Mars        3390      2
7  Neptune       24622     14

In [68]:
##logical operators
mask =( planets['moons'] <10) | (planets['moons'] > 50)
mask

0     True
1     True
2     True
3     True
4     True
5     True
6    False
7    False
Name: moons, dtype: bool

In [69]:
planets[mask]

    planet   radius_km  moons
0  Mercury        2440      0
1    Vanus        6052      0
2    Earth        6371      1
3     Mars        3390      2
4  Jupiter       69911     80
5   Setrun       58232     83

In [70]:
mask = (planets['moons'] > 20) & ~(planets['moons'] == 80) & ~(planets[' radius_km'] < 50000)
planets[mask]

   planet   radius_km  moons
5  Setrun       58232     83

In [92]:
data ={' planet': ['Mercury' , 'Vanus', 'Earth', 'Mars', 'Jupiter', 'Setrun', 'Uranus', 'Neptune'],
      'radius_km': [2440,6052,6371,3390,69911,58232,25362,24622],
       'moons': [0,0,1,2,80,83,27,14],
       'type': ['terrestrail', 'terrestrail', 'terrestrail', 'terrestrail', 'gas giant', 'gas giant',
                 'ice giant', 'ice giant'],
       'rings': ['no', 'no', 'no', 'no', 'yes', 'yes', 'yes', 'yes'],
       'mean_temp_c': [167, 464, 15, -65, -110, -140, -195, -200],
       'megnatic_fields': ['yes', 'no', 'yes', 'no', 'yes', 'yes', 'yes', 'yes']
      }
planets = pd.DataFrame(data)
planets

    planet  radius_km  moons         type rings  mean_temp_c megnatic_fields
0  Mercury       2440      0  terrestrail    no          167             yes
1    Vanus       6052      0  terrestrail    no          464              no
2    Earth       6371      1  terrestrail    no           15             yes
3     Mars       3390      2  terrestrail    no          -65              no
4  Jupiter      69911     80    gas giant   yes         -110             yes
5   Setrun      58232     83    gas giant   yes         -140             yes
6   Uranus      25362     27    ice giant   yes         -195             yes
7  Neptune      24622     14    ice giant   yes         -200             yes

In [93]:
planets.groupby(['type'])

In [94]:
planets.groupby('type').sum()

,planet,radius_km,moons,rings,mean_temp_c,megnatic_fields
type,,,,,,
gas giant,JupiterSetrun,128143,163,yesyes,-250,yesyes
ice giant,UranusNeptune,49984,41,yesyes,-395,yesyes
terrestrail,MercuryVanusEarthMars,18253,3,nononono,581,yesnoyesno

In [95]:
import pandas as pd
print(pd.__version__)

3.0.3

In [96]:
planets.groupby(['type']).sum()[['moons']]##insert column as list

             moons
type
gas giant      163
ice giant       41
terrestrail      3

In [97]:
planets.groupby(['type', 'megnatic_fields']).mean(numeric_only=True)

                             radius_km  moons  mean_temp_c
type        megnatic_fields
gas giant   yes                64071.5   81.5       -125.0
ice giant   yes                24992.0   20.5       -197.5
terrestrail no                  4721.0    1.0        199.5
            yes                 4405.5    0.5         91.0

In [98]:
planets.groupby('type')[['radius_km','moons','mean_temp_c']].agg(['mean','median'])

            radius_km           moons        mean_temp_c
                 mean   median   mean median        mean median
type
gas giant    64071.50  64071.5  81.50   81.5     -125.00 -125.0
ice giant    24992.00  24992.0  20.50   20.5     -197.50 -197.5
terrestrail   4563.25   4721.0   0.75    0.5      145.25   91.0

In [99]:
planets.groupby('type')[['radius_km','moons','mean_temp_c']].agg(['mean','max'])

            radius_km         moons     mean_temp_c
                 mean    max   mean max        mean  max
type
gas giant    64071.50  69911  81.50  83     -125.00 -110
ice giant    24992.00  25362  20.50  27     -197.50 -195
terrestrail   4563.25   6371   0.75   2      145.25  464

In [101]:
def percentile_90(x):
     return x.quantile(0.9)

In [102]:
planets.groupby('type')[['radius_km','moons','mean_temp_c']].agg(['mean',percentile_90])

            radius_km                moons               mean_temp_c  \
                 mean percentile_90   mean percentile_90        mean
type
gas giant    64071.50       68743.1  81.50          82.7     -125.00
ice giant    24992.00       25288.0  20.50          25.7     -197.50
terrestrail   4563.25        6275.3   0.75           1.7      145.25


            percentile_90
type
gas giant          -113.0
ice giant          -195.5
terrestrail         374.9

In [108]:
data ={' planet': ['Mercury' , 'Vanus', 'Earth', 'Mars'],
      ' radius_km': [2440,6052,6371,3390],
       'moons':[0,0,1,2]}
planets1 = pd.DataFrame(data)
planets1

    planet   radius_km  moons
0  Mercury        2440      0
1    Vanus        6052      0
2    Earth        6371      1
3     Mars        3390      2

In [135]:
data ={' planet': ['Jupiter', 'Setrun', 'Uranus', 'Neptune'],
      ' radius_km': [69911,58232,25362,24622],
       'moons':[80,83,27,14]}
planets2 = pd.DataFrame(data)
planets2

    planet   radius_km  moons
0  Jupiter       69911     80
1   Setrun       58232     83
2   Uranus       25362     27
3  Neptune       24622     14

In [136]:
df3 =pd.concat([planets1, planets2], axis=0)
df3

    planet   radius_km  moons
0  Mercury        2440      0
1    Vanus        6052      0
2    Earth        6371      1
3     Mars        3390      2
0  Jupiter       69911     80
1   Setrun       58232     83
2   Uranus       25362     27
3  Neptune       24622     14

In [137]:
df3 = df3.reset_index(drop=True)
df3

    planet   radius_km  moons
0  Mercury        2440      0
1    Vanus        6052      0
2    Earth        6371      1
3     Mars        3390      2
4  Jupiter       69911     80
5   Setrun       58232     83
6   Uranus       25362     27
7  Neptune       24622     14

In [138]:
planets

    planet   radius_km  moons
0  Jupiter       69911     80
1   Setrun       58232     83
2   Uranus       25362     27
3  Neptune       24622     14

In [139]:
planets

    planet   radius_km  moons
0  Jupiter       69911     80
1   Setrun       58232     83
2   Uranus       25362     27
3  Neptune       24622     14

In [143]:
print(df3.columns)
print(planets2.columns)

Index([' planet', ' radius_km', 'moons'], dtype='str')
Index([' planet', ' radius_km', 'moons'], dtype='str')