In [50]:
###assign the following lists of words##3
x = ['Now' , 'we ', 'are' , ' cooking ' , ' with ' , 7 ,' ingredients ' ]
print(x[2])

are

In [51]:
print(x[7])

IndexError: list index out of range

In [52]:
###use indices to get slice##
x[1:3]

['we ', 'are']

In [53]:
##use colons to get all words untill the  index slot 2###
x[:3]

['Now', 'we ', 'are']

In [54]:
####to leave one range index empty##
x[2:]

['are', ' cooking ', ' with ', 7, ' ingredients ']

In [55]:
##3 to check if list of word contain certain elements ###result will be boolean###
'this' in x

False

In [56]:
Fruites = [ ' pineapple ' , ' apple ' , ' orange ' ]
print(Fruites)

[' pineapple ', ' apple ', ' orange ']

In [57]:
##for adding element to list###
Fruites.append('kiwi')
print(Fruites)

[' pineapple ', ' apple ', ' orange ', 'kiwi']

In [58]:
Fruites.insert(1,'banana') ###function which takes two parameters###
print(Fruites)

[' pineapple ', 'banana', ' apple ', ' orange ', 'kiwi']

In [59]:
###element at begning of list###
Fruites.insert(0,'mango')
print(Fruites)

['mango', ' pineapple ', 'banana', ' apple ', ' orange ', 'kiwi']

In [60]:
###function for removing element from list using one parmeter##
Fruites.remove('mango')
print(Fruites)

[' pineapple ', 'banana', ' apple ', ' orange ', 'kiwi']

In [63]:
###pop()for removing element at given index###
Fruites.pop(2)
print(Fruites)

[' pineapple ', 'banana', 'kiwi']

In [65]:
##reassign value for poping element and replacing it with oher##
Fruites[1] = 'mango'
print(Fruites)

[' pineapple ', 'mango', 'kiwi']

In [72]:
power = '1.21'
power =  power  +  ' gigawatts'
print(power)

1.21 gigawatts

In [74]:
### can not overwrite character at index 0 in string ##
print[0] = 2

TypeError: 'builtin_function_or_method' object does not support item assignment

In [76]:
power = [1.21 ,' gigawatts ']###thats why lists are mutable##
power = 2.21
print(power)

2.21

In [79]:
Fullname = ('Masha' , 'Z' , 'Hopper')
print(Fullname)

('Masha', 'Z', 'Hopper')

In [81]:
Fullname = Fullname + ('jr',)
print(Fullname)

('Masha', 'Z', 'Hopper', 'jr')

In [83]:
Fullname = ['Masha' , 'Z' , 'Hopper']####no longer a ist so output without brackets###
Fullname = tuple(Fullname)
print(Fullname)

('Masha', 'Z', 'Hopper')

In [93]:
def to_dollars_cents(price):
    
  '''
 split price (float) into dollars and cents 
 '''
  dollars = int(price // 1)
  cents = round(price % 1 * 100)
  return dollars , cents ##3return value represented as tuple containing two values##

In [92]:
to_dollars_cents(6.55)

(6, 55)

In [97]:
dollars , cents = to_dollars_cents(6.55)###unpacking tuples###
print(dollars + 1)
print(cents + 1)

7
56

In [98]:
type(dollars)

int

In [59]:
team = [ ('marta' , 20 , 'center'),
         ('ana' , 22, 'playing ground'),
         ('gabi' ,23 , 'point guard'),
         ('luz' , 22 , 'shooting guard'),
         ('lorenze' , 24, 'small forward'),
       ] ####sigle tuple list###

In [39]:
for name , age , position in team:
    print(name)

marta
ana
gabi
luz
lorenze

In [40]:
for player in team:
    print(player[0])

marta
ana
gabi
luz
lorenze

In [48]:
def player_position(players):
    result = []
    for name , age , position in players:
        result.append('name: {:>19} \nposition: {:>15}\n'.format(name , position))###formating & new line##

    return result

In [49]:
for player in player_position(team):
    print(player)

name:               marta
position:          center

name:                 ana
position:  playing ground

name:                gabi
position:     point guard

name:                 luz
position:  shooting guard

name:             lorenze
position:   small forward

In [50]:
###nested loop###
for left in range(7):
    for right in range(left, 7):
        print(f"[{left}|{right}]",  end=" ")
    print("\n")

[0|0] [0|1] [0|2] [0|3] [0|4] [0|5] [0|6]

[1|1] [1|2] [1|3] [1|4] [1|5] [1|6]

[2|2] [2|3] [2|4] [2|5] [2|6]

[3|3] [3|4] [3|5] [3|6]

[4|4] [4|5] [4|6]

[5|5] [5|6]

[6|6]

In [51]:
dominoes = []
for left in range (7):
    for right in range (left , 7):
        dominoes.append((left,right))
dominoes

[(0, 0),
 (0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (0, 5),
 (0, 6),
 (1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (2, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (4, 4),
 (4, 5),
 (4, 6),
 (5, 5),
 (5, 6),
 (6, 6)]

In [53]:
dominoes[4][1]

4

In [55]:
###total number of pips on each domino##
pips_from_loop = []
for domino in dominoes:
    pips_from_loop.append(domino[0]+domino[1])
print(pips_from_loop)

[0, 1, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 7, 4, 5, 6, 7, 8, 6, 7, 8, 9, 8, 9, 10, 10, 11, 12]

In [58]:
pips_from_list_comp = [domino[0]+domino[1]for domino in dominoes]###list comprehension##

In [1]:
###dictonaries##
zoo = {
    'pen_1' : 'penguins' ,
    'pen_2' :  'zebras' ,      ####zoo is dictonery and pen is key
    'pen_3' :  'lions'
}
zoo['pen_2']

'zebras'

In [4]:
zoo = dict(
    pen_1 = 'penguins',
    pen_2 = 'zebras',
    pen_3 =  'lions'
)
zoo['pen_2']

'zebras'

In [5]:
zoo['pen_4'] = 'crocodile'
zoo

{'pen_1': 'penguins',
 'pen_2': 'zebras',
 'pen_3': 'lions',
 'pen_4': 'crocodile'}

In [3]:
team = [ ('marta' , 20 , 'center'),
         ('ana' , 22, 'point guard'),
         ('gabi' ,23 , 'shooting guard'),
         ('luz' , 22 , 'power forward'),
         ('lorenze' , 24, 'small forward'),
         ('msandra' , 19 , 'center'),
         ('Mari' , 18, 'point guard'),
         ('Esme' ,18 , 'shooting guard'),####create dictonery where position are keys and players are values
         ('Lin' , 18 , 'power forward'),
         ('Sol' , 19, 'small forward'),
       ]

In [7]:
new_team =  {}
for name, age , position in team:
    if position in new_team:
        new_team [position].append((name , age))###conversion of list into dictonery
    else:
        new_team[position] = [(name , age)]
new_team

{'center': [('marta', 20), ('msandra', 19)],
 'point guard': [('ana', 22), ('Mari', 18)],
 'shooting guard': [('gabi', 23), ('Esme', 18)],
 'power forward': [('luz', 22), ('Lin', 18)],
 'small forward': [('lorenze', 24), ('Sol', 19)]}

In [8]:
new_team['point guard']

[('ana', 22), ('Mari', 18)]

In [10]:
for x in new_team:    ####loop over dictonery position are keys of dictonery
    print(x)

center
point guard
shooting guard
power forward
small forward

In [11]:
new_team.keys()

dict_keys(['center', 'point guard', 'shooting guard', 'power forward', 'small forward'])

In [12]:
new_team.values()

dict_values([[('marta', 20), ('msandra', 19)], [('ana', 22), ('Mari', 18)], [('gabi', 23), ('Esme', 18)], [('luz', 22), ('Lin', 18)], [('lorenze', 24), ('Sol', 19)]])

In [14]:
for a , b in new_team.items():
      print(a , b)

center [('marta', 20), ('msandra', 19)]
point guard [('ana', 22), ('Mari', 18)]
shooting guard [('gabi', 23), ('Esme', 18)]
power forward [('luz', 22), ('Lin', 18)]
small forward [('lorenze', 24), ('Sol', 19)]

In [16]:
x = set(['foo' , 'bar' ,'baz','foo'])###each elemeent must be unique
print(x)

{'foo', 'baz', 'bar'}

In [17]:
x = set(('foo' , 'bar' , 'baz' , 'foo'))
print(x)

{'foo', 'baz', 'bar'}

In [20]:
###pass a string through set function##singular occurence of o and f in unoredered way##accept single argument
x = set('foo')
print(type(x))
##set with braces
y = {}
print(type(y))

<class 'set'>
<class 'dict'>

In [22]:
##literal inside braces
x = {'foo'}
print(x)

{'foo'}

In [ ]:
##to define an empety set use set() curly braces when  set is not empty

In [24]:
set1 = { 1 , 2 , 3 , 4 , 5 , 6 }##intersection meethood denoted by &
set2 = { 4 , 5 , 6 , 7 , 8 , 9 }

print(set1.intersection(set2))

print(set1 & set2)

{4, 5, 6}
{4, 5, 6}

In [29]:
x1 = {'foo', 'bar', 'baz'}
x2 = {'baz', 'quax', 'quaax'}
print(x1.union(x2))
print(x1 | x2)

{'bar', 'quax', 'baz', 'foo', 'quaax'}
{'bar', 'quax', 'baz', 'foo', 'quaax'}

In [32]:
set1 = {1, 2, 3, 4, 5, 6}
set2 = {4, 5, 6, 7, 8, 9}
print(set1.difference(set2))
print(set1 - set2)

{1, 2, 3}
{1, 2, 3}

In [34]:
print(set2.difference(set1))
print(set2 - set1)

{8, 9, 7}
{8, 9, 7}

In [35]:
set1 = {1, 2, 3, 4, 5, 6}
set2 = {4, 5, 6, 7, 8, 9}
print(set2.symmetric_difference(set1))
print(set2 ^ set1)

{1, 2, 3, 7, 8, 9}
{1, 2, 3, 7, 8, 9}

In [49]:
list_a = [1, 2, 3]
list_b = [2, 4, 6]

In [50]:
###numpy
list_c = []
for i in range(len(list_a)):
    list_c.append(list_b[i] * (list_a[i]))

list_c

[2, 8, 18]

In [53]:
import numpy as np
array_a = np.array(list_a)
array_b = np.array(list_b)

array_a * array_b

array([ 2,  8, 18])

In [54]:
import numpy as np ### by passing obj to ndARRAY
x = np.array([1, 2, 3, 4,])
x

array([1, 2, 3, 4])

In [56]:
x[-1] = 5
x

array([1, 2, 3, 5])

In [58]:
arr = np.array([1, 2, 3, 'coconut'])##u21 is unicode
arr

array(['1', '2', '3', 'coconut'], dtype='<U21')

In [61]:
print(type(arr))

<class 'numpy.ndarray'>

In [62]:
arr = np.array([1, 2, 3,])
arr.dtype

dtype('int64')

In [64]:
arr.shape###numpy takes array like obj of len x

(3,)

In [66]:
arr.ndim

1

In [72]:
arr_2d = np.array([[1, 2] ,[3, 4 ],[ 5, 6] ,[ 7, 8]])
print(arr_2d.shape)
print(arr_2d.ndim)
arr_2d

(4, 2)
2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [73]:
arr_2d = arr_2d.reshape(2 , 4)
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [74]:
arr = np.array([1, 2, 3, 4, 5])
np.mean(arr)

np.float64(3.0)

In [75]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [76]:
np.floor(5.7)

np.float64(5.0)

In [77]:
np.ceil(5.3)

np.float64(6.0)

In [78]:
####pandas##add functionlity to python core toolset
import numpy as np
import pandas as pd

In [84]:
dataframe = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
dataframe.head(25)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S

In [86]:
dataframe['Age'].mean()

np.float64(29.69911764705882)

In [87]:
dataframe.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200